# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  build:
    machine:
    # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/src/NiMARE
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE/
  get_data:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    - restore_cache:
          keys:
            - data-v1-{{ epoch }}
            - data-v1-
    - run:
          name: Get Neurovault Data from Collection 1425
          command: |
            mkdir -p /tmp/data
            if [[ ! -d "/tmp/data/21 pain studies (NIDM-Results)" ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O collection_1425.zip "https://neurovault.org/collections/1425/download"
              unzip xvzf collection_1425.zip -d /tmp/data/ &&\
              rm collection_1425.zip
            else
              echo "Dataset 1425 was cached"
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - data
      - save_cache:
         key: data-v1-{{ epoch }}
         paths:
            - /tmp/data
  testing:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp/src/NiMARE
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Install Testing Software
          command: |
            pip install \
              flake8 \
              coverage \
              coveralls \
              codecov \
              pytest \
              pytest-cov \
              "setuptools>=27.0" \
              cython \
              numpy \
              twine \
              docutils
      - run:
          name: Run flake8
          command: |
            flake8 nimare
      - run:
        name: Install NiMARE
        command: |
          python setup.py install
      - run:
          name: Run pytest
          command: |
            py.test --cov-report term-missing --cov=nimare nimare
      - run:
          name: Check Pypi Preconditions
          command: |
             python setup.py check -r -s
             python setup.py sdist

  deploy_pypi:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/NiMARE
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy to PyPi
          command: |
            pyenv global 3.5.2
            virtualenv venv
            pip install "setuptools>=27.0" cython numpy twine docutils
            # echo "${CIRCLE_TAG}" > fmriprep/VERSION
            # echo "include fmriprep/VERSION" >> MANIFEST.in
            python setup.py check -r -s
            python setup.py sdist
            twine upload dist/*
            cd wrapper && python setup.py sdist
            twine upload dist/*

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - testing:
          requires:
            - build
      - deploy_pypi:
          requires:
            - build
            - testing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
