# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  build:
    machine:
    # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/src/NiMARE
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE/
  testing:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp/src/NiMARE
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Install Testing Software
          command: |
            pip install flake8 coverage coveralls codecov pytest pytest-cov
      - run:
          name: Run flake8
          command: |
            flake8 nimare
      - run:
        name: Install NiMARE
        command: |
          python setup.py install
      - run:
          name: Run pytest
          command: |
            py.test --cov-report term-missing --cov=nimare nimare

  deploy_pypi:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/NiMARE
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy to PyPi
          command: |
            pyenv global 3.5.2
            virtualenv venv
            pip install "setuptools>=27.0" cython numpy twine docutils
            # echo "${CIRCLE_TAG}" > fmriprep/VERSION
            # echo "include fmriprep/VERSION" >> MANIFEST.in
            python setup.py check -r -s
            python setup.py sdist
            twine upload dist/*
            cd wrapper && python setup.py sdist
            twine upload dist/*

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - testing:
          requires:
            - build
      - deploy_pypi:
          requires:
            - build
            - testing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
